name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Deploy to server With
        run: |
          cd /home/ubuntu/Krishna/Full-Airbnb
          git pull origin master
          cd api
          npm install
          ls
          pm2 restart Airbnb-Api || pm2 start npm --name "Airbnb-Api" -- start
